### ISSUE TITLE
Error: env.stopOnSpecFailure is not a function with Jasmine v3.1.0

### ISSUE THREAD

**Issue by jaan** [dfederm/karma-jasmine-html-reporter#6]
I'm using Jasmine v3.1.0 with karma-jasmine-html-reporter v1.0.0 and i get this below error.

`
"message": "Uncaught TypeError: env.stopOnSpecFailure is not a function\nat node_modules/karma-jasmine-html-reporter/src/lib/adapter.js:26:7\n\nTypeError: env.stopOnSpecFailure is not a function\n    at node_modules/karma-jasmine-html-reporter/src/lib/adapter.js:26:7\n    at node_modules/karma-jasmine-html-reporter/src/lib/adapter.js:76:3",`

Note: It works with karma-jasmine-html-reporter v 0.2.2

**Comment by jaan** [comment]
Something to do with this change?
https://github.com/taras42/karma-jasmine-html-reporter/pull/32

**Comment by dfederm** [comment]
Are you sure you're using Jasmine 3+? `env.stopOnSpecFailure` is defined here:
https://github.com/jasmine/jasmine/blob/01a11133872d5cde8614213fde9c0d4a1f482f41/src/core/Env.js#L185 and was added in 3.0.0 as seen here: https://github.com/jasmine/jasmine/commit/e15f273f06c6b8c7902050fe500486c056802ed1

**Comment by dfederm** [comment]
Closing due to inactivity

**Comment by cormacrelf** [comment]
FWIW, I had this problem and it was because there were a few different versions of jasmine-core around, and html-reporter had picked up 2.99 even though jasmine-core 3.1.0 was right next to it. I changed the other packages in my monorepo to use 3.1.0 as well, and this problem went away.
