### ISSUE TITLE
Uncaught TypeError: env.hideDisabled is not a function

### ISSUE THREAD

**Issue by julian-bieringer** [dfederm/karma-jasmine-html-reporter#14]
Since upgrading from 1.2.0 to 1.3.0 I encounter two issues:

1.)

![image](https://user-images.githubusercontent.com/4979848/44325606-90039a80-a459-11e8-8f07-c4a559c3ea65.png)

![image](https://user-images.githubusercontent.com/4979848/44325792-07d1c500-a45a-11e8-998b-836010486f63.png)

2.)
![image](https://user-images.githubusercontent.com/4979848/44325625-9abe2f80-a459-11e8-9bf2-6f25dc851968.png)

When locking the version of your package to 1.2.0 or below, everythings working fine. Only since 1.3.0 these errors occur. Also there is no spec bar anymore showing the specs run due to the first error.

Maybe I am missing something but this is the only thing i could figure out.

**Comment by footballencarta** [comment]
I've experienced this too.

I updated jasmine-core to 3.2.1, and it seemed to work as expected.

**Comment by julian-bieringer** [comment]
Thanks a lot!

Hope the pull request gets merged :)

**Comment by dfederm** [comment]
Fixed in #15
